name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Theos and SDK
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          mkdir -p $HOME/theos/sdks
          curl -LO https://github.com/theos/sdks/archive/refs/heads/master.zip
          unzip master.zip
          mv sdks-master/iPhoneOS14.5.sdk $HOME/theos/sdks/
          rm -rf master.zip sdks-master

      - name: Install Build Tools
        run: brew install ldid make

      - name: Compile Tweak
        run: |
          export THEOS=$HOME/theos
          gmake package FINALPACKAGE=1

      - name: Upload Finished Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TweakPackage
          path: packages/*.deb
