name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Grab iOS SDK
        run: |
          mkdir -p theos/sdks
          curl -LO https://github.com/theos/sdks/archive/refs/heads/master.zip
          unzip master.zip
          mv sdks-master/iPhoneOS14.5.sdk theos/sdks/
          rm -rf master.zip sdks-master

      - name: Build Tweak
        uses: Randomblock1/theos-action@v1
        with:
          theos-dir: ./theos

      - name: Upload Everything Built
        uses: actions/upload-artifact@v4
        with:
          name: BuildOutput
          path: |
            .theos/
            packages/
            *.deb
